### ISSUE TITLE
main_gcn.py occurs error

### ISSUE THREAD

**Issue by christw16** [garyzhao/SemGCN#26]
Hi there~
Thank you for sharing this great work.

when I run main_gcn.py.
It occur this error, the code seems correct though.

Below are the error message:

Traceback (most recent call last):
  File "main_gcn.py", line 22, in <module>
    from models.sem_gcn import SemGCN
  File "/home/iis/SemGCN/models/sem_gcn.py", line 48
    self.nonlocal = GraphNonLocal(hid_dim, sub_sample=group_size)
                ^
SyntaxError: invalid syntax

Thank you~

**Comment by saichanda** [comment]
Hi @christw16,
You might find a reference to the error in issue[ #19 ](https://github.com/garyzhao/SemGCN/issues/19)

**Comment by christw16** [comment]
@saichanda  Hi there~

My python version is: 3.6.10
and I retype the function here. However is still not working....

**Comment by christw16** [comment]
it seems that it is nonLocal keywords problem.
